apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selectorLabels.app }}
      comp: {{ .Values.selectorLabels.comp }}
      tier: {{ .Values.selectorLabels.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabels.app }}
        comp: {{ .Values.selectorLabels.comp }}
        tier: {{ .Values.selectorLabels.tier }}
    spec:
      imagePullSecrets:
      - name: aeriOS-common-deployments
      containers:
      - name: hlo-frontend
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CB_URL
          value: "{{ .Values.EnvVar.url }}"
        - name: CB_PORT
          value: "{{ .Values.EnvVar.port }}"
        - name: BOOTSTRAP_SERVERS
          value: "{{ .Values.EnvVar.bootstrapServers }}"
        - name: GROUP_ID
          value: "{{ .Values.EnvVar.groupId }}"
        - name: AUTO_OFFSET_RESET
          value: "{{ .Values.EnvVar.autoOffsetReset }}"
        - name: PRODUCER_TOPIC
          value: "{{ .Values.EnvVar.producerTopic }}"
        - name: K8S_SHIM_URL
          value: "{{ .Values.EnvVar.k8sShimUrl }}"
        - name: K8S_SHIM_PORT
          value: "{{ .Values.EnvVar.k8sShimPort }}"
---

apiVersion: v1
kind: Service
metadata:
  name: hlo-fe-service
spec:
  selector:
      app: {{ .Values.selectorLabels.app }}
      comp: {{ .Values.selectorLabels.comp }}
      tier: {{ .Values.selectorLabels.tier }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{.Values.service.type}}